config/routes.rb
Rails.application.routes.draw do
  resources :signups, only: [:index, :create]
  resources :contact, only: [:index]

  root to: "cat_gifs#index"

  resources :cat_gifs do 
    member do 
      get "upvote"
      get "downvote"
    end

  end

end

app/models/cat_gif.rb
class CatGif < ActiveRecord::Base
end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cat_gifs_controller.rb
class CatGifsController < ApplicationController
  before_action :set_cat_gif, only: [:show, :upvote, :downvote, :edit, :update, :destroy]

  # GET /cat_gifs
  # GET /cat_gifs.json
  def index
    @cat_gifs = CatGif.all
    @cat_gifs = @cat_gifs.order(:id)

    # User for API's later
    # get_reddit_cats
    # clean_reddit_cat_gifs

    @signup = Signup.new
  end

  # GET /cat_gifs/1
  # GET /cat_gifs/1.json
  def show
  end

  def upvote
    @cat_gif.increment!(:score)
    redirect_to cat_gifs_path(anchor: "none") #seems to work because the id is actually missing from the page
  end

  def downvote
    @cat_gif.decrement!(:score)
    redirect_to cat_gifs_path(anchor: "none") #seems to work because the id is actually missing from the page
  end

  # GET /cat_gifs/new
  def new
    @cat_gif = CatGif.new
  end

  # GET /cat_gifs/1/edit
  def edit
  end

  # POST /cat_gifs
  # POST /cat_gifs.json
  def create
    @cat_gif = CatGif.new(cat_gif_params)

    respond_to do |format|
      if @cat_gif.save
        format.html { redirect_to @cat_gif, notice: 'Cat gif was successfully created.' }
        format.json { render :show, status: :created, location: @cat_gif }
      else
        format.html { render :new }
        format.json { render json: @cat_gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_gifs/1
  # PATCH/PUT /cat_gifs/1.json
  def update
    respond_to do |format|
      if @cat_gif.update(cat_gif_params)
        format.html { redirect_to @cat_gif, notice: 'Cat gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat_gif }
      else
        format.html { render :edit }
        format.json { render json: @cat_gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_gifs/1
  # DELETE /cat_gifs/1.json
  def destroy
    @cat_gif.destroy
    respond_to do |format|
      format.html { redirect_to cat_gifs_url, notice: 'Cat gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cat_gif
    @cat_gif = CatGif.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cat_gif_params
    params.require(:cat_gif).permit(:title, :url, :score)
  end

  def get_reddit_cats
    #Make the HTTP request:
    reddit_data = RestClient.get("https://www.reddit.com/r/CatGifs/.json")

    #Parse the stuff we care about: response.body
    results = JSON.parse(reddit_data.body)

    #Save the data to an array of cats. 
    @reddit_cat_gifs = results["data"]["children"]
  end

  # This is well, un-good code
  def clean_reddit_cat_gifs
    @cleaned_reddit_cat_gifs =  []

    @reddit_cat_gifs.each do |cat_gif|
      if cat_gif["data"]["url"].include? ".gif"
        if cat_gif["data"]["url"].include? ".gifv"
          bad_url = cat_gif["data"]["url"]
          good_url = bad_url.gsub(/.gifv/, '.gif')
          cat_gif["data"]["url"] = good_url
          @cleaned_reddit_cat_gifs << cat_gif
        else
          @cleaned_reddit_cat_gifs << cat_gif
        end
      end

      @cleaned_reddit_cat_gifs << cat_gif if cat_gif["data"]["url"].include? ".jpg"
      @cleaned_reddit_cat_gifs << cat_gif if cat_gif["data"]["url"].include? ".jpeg"
      @cleaned_reddit_cat_gifs << cat_gif if cat_gif["data"]["url"].include? ".jif"
      @cleaned_reddit_cat_gifs << cat_gif if cat_gif["data"]["url"].include? ".png"
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render :show, status: :created, location: @signup }
      else
        format.html { render :new }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:email_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_gifs_helper.rb
module CatGifsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/cat_gifs/_form.html.erb
<%= form_for(@cat_gif) do |f| %>
  <% if @cat_gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat_gif.errors.count, "error") %> prohibited this cat_gif from being saved:</h2>

      <ul>
      <% @cat_gif.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cat_gifs/edit.html.erb
<h1>Editing Cat Gif</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat_gif %> |
<%= link_to 'Back', cat_gifs_path %>

app/views/cat_gifs/index.html.erb
  <!-- Image Background Page Header -->
  <!-- Note: The background image is set within the business-casual.css file. -->
  <header class="business-header">
    <div class="container">
      <div class="row">
        <div class="title col-sm-12">
          <h1 class="tagline">Catster</h1>
          <h2 class="subtitle">Making the world better by adding cats</h2>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <hr>
  
    <div class="row new-cat">
      <div class="col-sm-12">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h1 class="panel-title">Get a new cat in your inbox daily</h3>
            </div>
            <div class="panel-body">
              <%= form_for @signup, html: {class: "form-inline text-center"} do |f| %>
                <div class="form-group">
                  <%= f.email_field :email_address, class: "form-control input-lg", size: 50, placeholder: "david@catster.com" %>
                </div>  
                <%= f.submit "Signup", class: "btn btn-primary btn-lg signup-button" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <hr>

      <div class="row all-cats">
        <%- @cat_gifs.each do |cat_gif| %>
          <div class="col-sm-4" id=<%= cat_gif.id %>>
            <div class="cat-gif img-circle img-center" style="background-image:url(<%= cat_gif.url %>)"></div>
            <div class="vote">
              <span class="score">
                <%= cat_gif.score || 0 %>
              </span>
              <%= link_to"/cat_gifs/#{cat_gif.id}/upvote", class: "btn btn-default btn-lg up" do %>
                <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                UpVote
              <% end %>
                
              <%= link_to "/cat_gifs/#{cat_gif.id}/downvote", class: "btn btn-default btn-lg down" do %>
                <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
                DownVote
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="col-sm-4">
          <%= link_to "Add a Cat", new_cat_gif_path, class: "btn btn-success btn-lg btn-add-cat right" %>
       </div>
     </div>
     <!-- /.row -->

     <div class="row">
      <%- if @cleaned_reddit_cat_gifs.present? %>
        <h2>Reddit Cats</h2>
        <%- @cleaned_reddit_cat_gifs.each do |cat_gif| %>
          <div class="col-sm-4 mt40">
            <div class="cat-gif img-circle img-center" style="background-image:url(<%= cat_gif["data"]["url"] %>)"></div>
          </div>
        <% end %>
      <% end %>
     </div>
  </div>
  <br>

app/views/cat_gifs/new.html.erb
<h1>New Cat Gif</h1>

<%= render 'form' %>

<%= link_to 'Back', cat_gifs_path %>

app/views/cat_gifs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cat_gif.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @cat_gif.url %>
</p>

<p>
  <strong>Score:</strong>
  <%= @cat_gif.score %>
</p>

<%= link_to 'Edit', edit_cat_gif_path(@cat_gif) %> |
<%= link_to 'Back', cat_gifs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing Signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Signups</h1>

<table>
  <thead>
    <tr>
      <th>Email address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signups.each do |signup| %>
      <tr>
        <td><%= signup.email_address %></td>
        <td><%= link_to 'Show', signup %></td>
        <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
        <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signup', new_signup_path %>

app/views/signups/new.html.erb
<h1>New Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email address:</strong>
  <%= @signup.email_address %>
</p>

<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>